version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/predict
